version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=imaginamos
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80" 

#  imaginamos:
#    image: imaginamos:local
#    container_name: imaginamos
#    build:
#      context: .
#      dockerfile: Dockerfile.imaginamos-test
#    ports:
#      - 3000:3000
#    volumes:
#      - .:/app

#  tv-serv:
#    image: tv-serv:local
#    container_name: tv-serv
#    build:
#      context: .
#      dockerfile: Dockerfile.tv-serv
#    volumes:
#      - .:/app */     